config/routes.rb
Rails.application.routes.draw do

  # 最初に表示するページの設定
  root to: 'homes#top'

  # resources :books
  post 'books' => 'books#create'
  get 'show' => 'books#show'
  get 'books/:id/edit' => 'books#edit', as:'edit_book'
  get 'books/:id' => 'books#show', as: 'book'
  patch 'books/:id' =>'books#update', as:'update_book'
  get '/books' => 'books#index'
  delete 'books/:id' =>'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    #createへの受け渡し
    @books = Book.all
    #Book（保存してあるデータ）を全取得
  end


  def create
    # データを受け取り新規登録するためのインスタンス作成
    @book = Book.new(book_params)

    # データをデータベースに保存するためのsaveメソッド実行
    if @book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      # `books/books`というビューファイルを表示するための命令
      @books = Book.all
      # →　@listsが空になっているため、再度定義する。

      render :index
    end
  end


  def show
    @book = Book.find(params[:id])
  end


  def edit
    @book = Book.find(params[:id])
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books', notice: 'Book was successfully destroyed.'
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
    # params:formから送られてくるデータ
    # require:送られてきたデータから、モデル名:bookを指定し、データを絞り込む。
    # permit:requireで絞ったデータ野中から、保存を許可するｶﾗﾑを指定
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/books.html.erb
<h1>Books</h1>

<p>title</p>
<p>body</p>

<% @books.each do |book| %>
  <span>
    <%= book.title %>
    <%= book.body %>
    <%= link_to 'Show', book_path(book.id) %>

    <!--link_toメソッドではデフォルトでリンク先をshowアクションに設定しています。
    Editをクリックした際には、editアクションにリンクする必要があります。

    そのため、`link_to`メソッドの第二引数に`edit_book_path`ヘルパーメソッドを
    使用するように変更します。-->

    <%= link_to 'Edit', edit_book_path(book.id) %>
    <%= link_to 'Destroy', book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>

  </span>

<% end %>
<!--<p>edit</p>-->
<!--<p>destroy</p>-->







<!-- form_with部分 -->

<h1>New book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book, url:'/books', method: :post do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>
<% end %>

app/views/books/edit.html.erb
<h2>Editing Book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

  <p>Title</p>
  <%= f.text_field :title %>

  <p>Body</p>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>

<% end %>

<div class="inline-links-edit">
  <%= link_to 'Show', "/books/#{@book.id}" %>
  <p>|</p>
  <%= link_to 'Back', "/books" %>
</div>

app/views/books/index.html.erb
<div class="index">
  <h2>Books</h2>

  <style>
    td:nth-child(1) {
      width: 100px;
    }
    td:nth-child(2) {
      width: 200px;
    }

    td:nth-child(3),
    td:nth-child(4),
    td:nth-child(5) {
      width: 30px;
    }
  </style>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th> </th>
        <th> </th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book_path(book.id) %></td>
        <td><%= link_to 'Edit', edit_book_path(book.id) %></td>
        <td><%= link_to 'Destroy', book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>

      </tr>
      <% end %>
    </tbody>
  </table>

      <!--link_toメソッドではデフォルトでリンク先をshowアクションに設定しています。
      Editをクリックした際には、editアクションにリンクする必要があります。

      そのため、`link_to`メソッドの第二引数に`edit_book_path`ヘルパーメソッドを
      使用するように変更します。-->



  <!-- form_with部分 -->

  <h2>New book</h2>
  <% if @book.errors.any? %>
    <%= @book.errors.count %> errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>


  <%= form_with model: @book, url:'/books', method: :post do |f| %>

  <div class="index-edit">
    <p>Title</p>
    <%= f.text_field :title %>
  
    <p>Body</p>
    <%= f.text_area :body %>
  
    <%= f.submit 'Create Book' %>
  </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="show">
  <p>
    <strong>Title:</strong>
    <%= @book.title %>
  </p>
  
  <p>
    <strong>Body:</strong>
    <%= @book.body %>
  </p>
</div>

<!---->
<div class="inline-links-show">
  <%= link_to 'Edit', "/books/#{@book.id}/edit" %>
  <p>|</p>
  <%= link_to 'Back', "/books" %>
</div>

app/views/homes/top.html.erb
<h1>
  ようこそ
  <strong>Bookers</strong>
  へ！
</h1>

<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や<br>
  印象を共有し交換することができます
</p>

<%= link_to 'start', "/books" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>


</html>